version: "3.8"

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: graphql_demo
    ports:
      - "3306:3306"
    # volumes:
    #   - ./pgdata:/var/lib/mysql/data
  # postgesql:
  #   image: postgres:latest
  #   container_name: graphql-postgresql
  #   ports:
  #     - "5432:5432"
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=graphql_demo
  #   volumes:
  #     - ./pgdata:/var/lib/postgresql/data
  #     # copy the sql script to create tables
  #     # - ./db/migrations/20200413055140_CreateTasks.sql:/docker-entrypoint-initdb.d/20200413055140_CreateTasks.sql
  #     # copy the sql script to fill tables
  #     # - ./migrations/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
  #   # networks:
  #   #   - web_api